# utils/medical_abbreviations.py
# ─────────────────────────────────────────────────────────────────────────────
# Comprehensive medical abbreviation dictionary
# Used by the preprocessor to expand shorthand before NLP processing
# ─────────────────────────────────────────────────────────────────────────────

MEDICAL_ABBREVIATIONS = {

    # ── Patient & Demographics ─────────────────────────────────────────────
    "pt":     "patient",
    "pts":    "patients",
    "m":      "male",
    "f":      "female",
    "yo":     "year old",
    "y/o":    "year old",
    "yom":    "year old male",
    "yof":    "year old female",
    "dob":    "date of birth",
    "hx":     "history",
    "h/o":    "history of",
    "pmh":    "past medical history",
    "psh":    "past surgical history",
    "fh":     "family history",
    "sh":     "social history",
    "fhx":    "family history",
    "cc":     "chief complaint",

    # ── Symptoms & Presentation ────────────────────────────────────────────
    "c/o":    "complains of",
    "s/o":    "suggestive of",
    "r/o":    "rule out",
    "w/":     "with",
    "w/o":    "without",
    "s/p":    "status post",
    "sx":     "symptoms",
    "dx":     "diagnosis",
    "ddx":    "differential diagnosis",
    "rx":     "prescription",
    "tx":     "treatment",
    "sob":    "shortness of breath",
    "doe":    "dyspnea on exertion",
    "cp":     "chest pain",
    "ha":     "headache",
    "n/v":    "nausea and vomiting",
    "n/v/d":  "nausea vomiting and diarrhea",
    "abd":    "abdominal",
    "lbp":    "lower back pain",

    # ── Vitals ─────────────────────────────────────────────────────────────
    "bp":     "blood pressure",
    "hr":     "heart rate",
    "rr":     "respiratory rate",
    "temp":   "temperature",
    "spo2":   "oxygen saturation",
    "o2 sat": "oxygen saturation",
    "bmi":    "body mass index",
    "wt":     "weight",
    "ht":     "height",
    "map":    "mean arterial pressure",

    # ── Physical Exam ──────────────────────────────────────────────────────
    "pe":     "physical examination",
    "heent":  "head eyes ears nose throat",
    "cv":     "cardiovascular",
    "resp":   "respiratory",
    "gi":     "gastrointestinal",
    "gu":     "genitourinary",
    "msk":    "musculoskeletal",
    "neuro":  "neurological",
    "a&o":    "alert and oriented",
    "a&ox3":  "alert and oriented times three",
    "nad":    "no acute distress",
    "wnl":    "within normal limits",
    "nab":    "no abnormality detected",
    "rrr":    "regular rate and rhythm",
    "ctab":   "clear to auscultation bilaterally",
    "ntnd":   "non-tender non-distended",

    # ── Cardiovascular ─────────────────────────────────────────────────────
    "mi":     "myocardial infarction",
    "stemi":  "ST elevation myocardial infarction",
    "nstemi": "non ST elevation myocardial infarction",
    "chf":    "congestive heart failure",
    "cad":    "coronary artery disease",
    "afib":   "atrial fibrillation",
    "svt":    "supraventricular tachycardia",
    "vt":     "ventricular tachycardia",
    "vf":     "ventricular fibrillation",
    "pci":    "percutaneous coronary intervention",
    "cabg":   "coronary artery bypass grafting",
    "dvt":    "deep vein thrombosis",
    "pe_d":   "pulmonary embolism",
    "htn":    "hypertension",
    "hld":    "hyperlipidemia",
    "lvef":   "left ventricular ejection fraction",
    "echo":   "echocardiogram",
    "ecg":    "electrocardiogram",
    "ekg":    "electrocardiogram",

    # ── Respiratory ────────────────────────────────────────────────────────
    "copd":   "chronic obstructive pulmonary disease",
    "cap":    "community acquired pneumonia",
    "hap":    "hospital acquired pneumonia",
    "ards":   "acute respiratory distress syndrome",
    "osa":    "obstructive sleep apnea",
    "uri":    "upper respiratory infection",
    "lri":    "lower respiratory infection",
    "pft":    "pulmonary function test",
    "fev1":   "forced expiratory volume in one second",
    "fvc":    "forced vital capacity",
    "cpap":   "continuous positive airway pressure",
    "bipap":  "bilevel positive airway pressure",
    "intub":  "intubation",

    # ── Endocrine & Metabolic ─────────────────────────────────────────────
    "dm":     "diabetes mellitus",
    "dm1":    "type 1 diabetes mellitus",
    "dm2":    "type 2 diabetes mellitus",
    "t2dm":   "type 2 diabetes mellitus",
    "t1dm":   "type 1 diabetes mellitus",
    "hba1c":  "hemoglobin A1c",
    "fbs":    "fasting blood sugar",
    "rbs":    "random blood sugar",
    "tsh":    "thyroid stimulating hormone",
    "t3":     "triiodothyronine",
    "t4":     "thyroxine",
    "hypo":   "hypothyroidism",
    "hyper":  "hyperthyroidism",

    # ── Neurology ──────────────────────────────────────────────────────────
    "cva":    "cerebrovascular accident",
    "tia":    "transient ischemic attack",
    "loc":    "loss of consciousness",
    "gcs":    "glasgow coma scale",
    "mri":    "magnetic resonance imaging",
    "ct":     "computed tomography",
    "eeg":    "electroencephalogram",
    "ms":     "multiple sclerosis",
    "sz":     "seizure",
    "ams":    "altered mental status",

    # ── Renal ──────────────────────────────────────────────────────────────
    "aki":    "acute kidney injury",
    "ckd":    "chronic kidney disease",
    "esrd":   "end stage renal disease",
    "bun":    "blood urea nitrogen",
    "cr":     "creatinine",
    "egfr":   "estimated glomerular filtration rate",
    "hd":     "hemodialysis",
    "uti":    "urinary tract infection",
    "ua":     "urinalysis",

    # ── GI ─────────────────────────────────────────────────────────────────
    "gerd":   "gastroesophageal reflux disease",
    "ibs":    "irritable bowel syndrome",
    "ibd":    "inflammatory bowel disease",
    "cd":     "crohn's disease",
    "uc":     "ulcerative colitis",
    "lgib":   "lower gastrointestinal bleed",
    "ugib":   "upper gastrointestinal bleed",
    "egd":    "esophagogastroduodenoscopy",

    # ── Lab Values ─────────────────────────────────────────────────────────
    "cbc":    "complete blood count",
    "bmp":    "basic metabolic panel",
    "cmp":    "comprehensive metabolic panel",
    "lft":    "liver function tests",
    "lfts":   "liver function tests",
    "inr":    "international normalized ratio",
    "ptt":    "partial thromboplastin time",
    "pt_lab": "prothrombin time",
    "wbc":    "white blood cell count",
    "rbc":    "red blood cell count",
    "hgb":    "hemoglobin",
    "hct":    "hematocrit",
    "plt":    "platelet count",
    "na":     "sodium",
    "k":      "potassium",
    "cl":     "chloride",
    "co2":    "carbon dioxide",
    "ca":     "calcium",
    "mg":     "magnesium",
    "phos":   "phosphorus",
    "alt":    "alanine aminotransferase",
    "ast":    "aspartate aminotransferase",
    "alp":    "alkaline phosphatase",
    "tbili":  "total bilirubin",
    "dbili":  "direct bilirubin",
    "ldl":    "low density lipoprotein",
    "hdl":    "high density lipoprotein",
    "tg":     "triglycerides",
    "ck":     "creatine kinase",
    "trop":   "troponin",
    "bnp":    "brain natriuretic peptide",
    "crp":    "c-reactive protein",
    "esr":    "erythrocyte sedimentation rate",
    "psa":    "prostate specific antigen",

    # ── Medications & Routes ───────────────────────────────────────────────
    "po":     "by mouth",
    "iv":     "intravenous",
    "im":     "intramuscular",
    "sc":     "subcutaneous",
    "sl":     "sublingual",
    "top":    "topical",
    "inh":    "inhaled",
    "pr":     "per rectum",
    "ng":     "nasogastric",
    "prn":    "as needed",
    "qd":     "once daily",
    "bid":    "twice daily",
    "tid":    "three times daily",
    "qid":    "four times daily",
    "qhs":    "at bedtime",
    "q4h":    "every four hours",
    "q6h":    "every six hours",
    "q8h":    "every eight hours",
    "q12h":   "every twelve hours",
    "ac":     "before meals",
    "pc":     "after meals",
    "sos":    "if needed",
    "stat":   "immediately",
    "mg":     "milligrams",
    "mcg":    "micrograms",
    "gm":     "grams",
    "ml":     "milliliters",
    "mEq":    "milliequivalents",

    # ── Oncology ───────────────────────────────────────────────────────────
    "ca_onc": "cancer",
    "chemo":  "chemotherapy",
    "xrt":    "radiation therapy",
    "bx":     "biopsy",
    "mets":   "metastases",
    "nhl":    "non-hodgkin lymphoma",
    "hl":     "hodgkin lymphoma",
    "aml":    "acute myeloid leukemia",
    "cml":    "chronic myeloid leukemia",
    "all":    "acute lymphoblastic leukemia",

    # ── Procedures & Imaging ───────────────────────────────────────────────
    "cxr":    "chest x-ray",
    "kub":    "kidney ureter bladder x-ray",
    "us":     "ultrasound",
    "echo_p": "echocardiography",
    "lp":     "lumbar puncture",
    "or":     "operating room",
    "icu":    "intensive care unit",
    "ed":     "emergency department",
    "er":     "emergency room",
    "dc":     "discharge",
    "d/c":    "discharge",
    "adm":    "admission",
    "f/u":    "follow up",
    "ama":    "against medical advice",
    "npo":    "nothing by mouth",
    "tpn":    "total parenteral nutrition",
    "picc":   "peripherally inserted central catheter",
    "cvl":    "central venous line",
    "foley":  "foley catheter",

    # ── Infectious Disease ─────────────────────────────────────────────────
    "hiv":    "human immunodeficiency virus",
    "aids":   "acquired immunodeficiency syndrome",
    "hbv":    "hepatitis B virus",
    "hcv":    "hepatitis C virus",
    "mrsa":   "methicillin resistant staphylococcus aureus",
    "vre":    "vancomycin resistant enterococcus",
    "ssti":   "skin and soft tissue infection",
    "abx":    "antibiotics",
    "cx":     "culture",
    "bc":     "blood culture",
}


# Common medical section headers used in clinical notes
SECTION_HEADERS = [
    "chief complaint",
    "history of present illness",
    "hpi",
    "past medical history",
    "pmh",
    "past surgical history",
    "family history",
    "social history",
    "review of systems",
    "ros",
    "medications",
    "allergies",
    "physical examination",
    "vital signs",
    "general",
    "cardiovascular",
    "respiratory",
    "abdomen",
    "neurological",
    "assessment",
    "plan",
    "assessment and plan",
    "impression",
    "diagnosis",
    "discharge summary",
    "discharge medications",
    "follow up",
    "laboratory results",
    "imaging",
    "procedures",
]


def get_abbreviation_map() -> dict:
    """Return the full abbreviation dictionary."""
    return MEDICAL_ABBREVIATIONS


def get_section_headers() -> list:
    """Return list of known medical section headers."""
    return SECTION_HEADERS
